### ISSUE TITLE
Raise an error if the :message option is missing on checks

### ISSUE THREAD

**Issue by sunny** [sunny/actor#100]
[As reported](https://github.com/sunny/actor/pull/97/files#r1014905545) by @Buzzkill-McSquare, it would be better for checks to raise an error if the `:message` option isn’t provided. (Or make sure it uses the default.)

This should probably wait for #97 to be merged.

**Comment by sunny** [comment]
Now that #97 has been merged, @Buzzkill-McSquare would you like to create a PR with your suggestion? 🙏🏻

**Comment by Buzzkill-McSquare** [comment]
I can look into doing it this weekend.

**Comment by sunny** [comment]
Hey @Buzzkill-McSquare, small reminder here. No pressure, just want to know if you’re still interested in fixing this :)

**Comment by Buzzkill-McSquare** [comment]
Sorry man, I moved jobs and no longer use the gem so it's been in the far back of my mind. I can try to work on it when I have the time, but if anyone else wants to try to tackle it then feel free to.

**Comment by ArturGin** [comment]
Hey @sunny I took a crack at it and it seems to work. Cannot figure out how to create a pull request for a review. Is it an access issue or did I miss some guide somewhere?
p.s new to open source, perhaps there is a standard way to do it

**Comment by sunny** [comment]
Hey ArturGin! Thank you for your help on this, it’s much appreciated. I’m glad you chose this gem as your first open source Pull-Request 🤗

On GitHub, you should start by forking the gem. You’ll then have a copy of the project at `github.com/ArturGin/actor`. You can then create a new branch, commit to it and push it to your fork. Once you’ve pushed, visit your fork and GitHub should prompt you to create a new Pull Request for this new branch.

Let me know if you get stuck on any part of the way, I’ll try and help you out as best I can.

**Comment by ArturGin** [comment]
@sunny I did it! Yohooo, thank you for the instructions) It turned out that I just need to use Google more..

Now to the actual contents:
- Instead of throwing up an error, I decided to set missing message key to DEFAULT_MESSAGE in of the checks

**Comment by sunny** [comment]
Fixed by #117. Congratulations on your first merged open source PR @ArturGin 🎉

**Comment by ArturGin** [comment]
@sunny yohooo 🎆 !!
