### ISSUE TITLE
alias_input is documented but unavailable

### ISSUE THREAD

**Issue by jamesarosen** [sunny/actor#102]
The new `Playable.alias_input` is [documented in the README](https://github.com/sunny/actor/blob/main/README.md#input-aliases) but is not available in [3.4.1](https://github.com/sunny/actor/blob/c0361585acf6a83a544dc27d9a79f8e6c7c2308c/lib/service_actor/playable.rb), the latest release.

The docs also reference both `alias_input` and `input_alias`. The former exists on `main`. The latter doesn't exist anywhere.

**Comment by sunny** [comment]
Thank you for reporting this! The typo is fixed in the README (you should use `alias_input`) and a new version 3.5.0 has been released with the new feature 🎉
