### ISSUE TITLE
Missing note on stubbing ServiceActor::Result

### ISSUE THREAD

**Issue by schmijos** [sunny/actor#118]
I'm trying to fake a service actor result in a Rails request spec. The test I would like to write looks like this:

```rb
context 'when search fails (e.g. because of HTTP 503 on Google side)' do
  let(:params) { { query: 'Darkstorm Galaxy' } }

  before do
    allow(Google::AutocompletePlaces).to receive(:result).and_return(
      instance_double(ServiceActor::Result, success?: false, error: 'lol')
    )
  end

  it 'returns suggestions' do
    get api_authenticated_address_search_suggestions_path, params: params, headers: auth_headers

    expect(response).to have_http_status(:service_unavailable)
    expect(response.parsed_body).to include('application_errors' => be_a(String))
  end
end
```

But this doesn't work because `error` is derived from `method_missing`. And I shouldn't use `double` because of _RSpec_ best practices enforced by _rubocop_.

What's your take on that?

**Comment by sunny** [comment]
RSpec couldn’t be able to know what methods are defined on results since these methods only make sense at the end.

We *could* define an `error` method on `ServiceActor::Result` for this specific use case, as it’s an encouraged method name. However, this still wouldn’t work for other defined outputs.

You could use an `instance_double` and stub it as such:

```rb
let(:result) { instance_double ServiceActor::Result }

before do
  allow(Google::AutocompletePlaces).to receive(:result).and_return(result)
  allow(result).to receive(:success?).and_return(true)
  allow(result).to receive(:error).and_return("lol")
  allow(result).to receive(:places).and_return([])
end
```

In my case, I simply use `double` and disable this cop:

```yml
# Allow the use of `double`
RSpec/VerifiedDoubles:
  Enabled: false
```

**Comment by fidalgo** [comment]
For those landing here but living on the minitest land: https://fidalgo.pt/2023/07/23/service-objects-in-the-wild.html
(shameless plug)

**Comment by sunny** [comment]
Great thorough article! I’ve added it to the list of resources on [the wiki](https://github.com/sunny/actor/wiki)

**Comment by sunny** [comment]
I’m closing this issue, but feel free to discuss/reopen if you think of a better way to handle this.
