### ISSUE TITLE
Consider dropping support for unmaintained Ruby releases

### ISSUE THREAD

**Issue by viralpraxis** [sunny/actor#125]
The gem requires Ruby >= 2.4

https://github.com/sunny/actor/blob/0c8717e24b22d2d9a7d791cccfd09529fcee2bfd/service_actor.gemspec#L35

but that versions EOLed 3 years ago, I'd suggest to bump `required_ruby_version` to `>= 3.0` or at least `>= 2.7'

**Comment by sunny** [comment]
Absolutely! Tests are only running at a minimum of 2.7 so it wasn’t actually maintained to 2.4.
