### ISSUE TITLE
Make Actor result + pattern matching more pleasant

### ISSUE THREAD

**Issue by stephannv** [sunny/actor#133]
Hi, I'm using sunny/actor on my projects and I like it a lot, thanks for this awesome project.

I'm doing some experiments with pattern matching + Result but I noticed some issues, for example:

My expectation:
```ruby
case CreateUser.result(attributes: user_params)
in {success: true, user:}
  redirect_to user_path(user), notice: "success"
in {error: :invalid_record, user:}
  render "new", locals: { user: user }
in {error: :other_error}
  # do something else
end
```

But it can't be achieve because:

1) `case CreateUser.result(attributes: user_params)`
To have acess to succes/failure key, I need to use `.to_h` on `result`

2) `in {success: true, user:}`
`result.to_h` doesn't return `success` key, and returns `failure?` key only if `failure?` is true

So I have to write something like:
```ruby
result = CreateUser.result(attributes: user_params)

case result.to_h
in {failure?: true, error: :invalid_record, user:}
  render "new", locals: { user: user }
in {error: :other_error}
  # do something else
in {user:}
  redirect_to, user_path(user), notice: "success"
end
```

I'm not an expert on Pattern Matching, so I'm not sure if I'm on the right way. So I tried adding a `#deconstruct_keys` to ServiceActor::Result and it worked fine:

```ruby
def deconstruct_keys(keys)
  to_h.merge(success: success?, failure: failure?)
end
```

What do you think? If you are interested on this, I can try opening a PR with a first take on this.

**Comment by sunny** [comment]
Awesome! I haven’t used pattern matching enough and this will be a great opportunity to try it more on my projects. 👏🏻
