### ISSUE TITLE
Using `Kernel.tap` and `Kernel.then` via `ServiceActor::Result` receiver

### ISSUE THREAD

**Issue by viralpraxis** [sunny/actor#141]
https://github.com/sunny/actor/pull/138 made `Result` class inherit from `BasicObject`. One thing I missied is that now it's impossible to call `tap`/`then` on service result:

```ruby
SomeActor.call.tap { do_something(_1) }
SomeActor.call.then { _1.some_output = ... }
```

I think we can add these methods because collisions here are unlikely to happen and it seems reasonable in general

**Comment by sunny** [comment]
Sure, it makes sense, I feel that they are known enough to be unavailable as inputs 👍🏻
