### ISSUE TITLE
Is `DefaultCheck` obsolete?

### ISSUE THREAD

**Issue by viralpraxis** [sunny/actor#144]
I struggle to figure out in which case DefaultCheck is used.

Seems like `return if @result.key?(@input_key)` (lib/service_actor/checks/default_check.rb:54) is always evaluated to `true` (both in specs and real-world scenarios).

1. `Defaultable` (which runs first) sets the default is required
2. `NiCheck` (runs second) raise if nil
3. Finally `DefaultCheck.check` is fired and has nothing to do

Am I missing something?

**Comment by sunny** [comment]
You’re right. I think the intent was to move it to a check, but was never fully moved. We can safely remove it. 🧹

**Comment by viralpraxis** [comment]
Hey @sunny 👋🏻 Any plans on releasing new version?

**Comment by sunny** [comment]
I guess now could be a good time. I’ll prepare that.

**Comment by sunny** [comment]
Released as v3.8.0 🎉
