### ISSUE TITLE
BasicObject a bit too restrictive as an inheritance of ServiceActor::Result

### ISSUE THREAD

**Issue by thierry-tranchant** [sunny/actor#168]
Hello,

I have been struggling with a bump from 3.7.0 to 3.9.3 because of the new inheritance of `ServiceActor::Result`. I need to use the `an_instance_of?` matcher from Rspec in a test where I just need to check a job is set with a `ServiceActor::Result` argument. The aim of this job is not to test the content of the result (tested elsewhere), that's why I used this matcher.

My problem is that this matcher uses `Object#hash` and `Object#instance_of?` methods that we cannot use anymore because `OpenStruct` inheritance was dropped (`OpenStruct` inherits from `Object`).

The solution could be to replicate those methods or to make the class inherit from `Object`. I have a preference for the latter.

What do you think ?

**Comment by sunny** [comment]
I guess `#instance_of?` makes a lot of sense to add to results. The `#hash` is a method name that unfortunately could be used as an input as well, but is such a basic building block of Ruby that we should probably also add it to results.

Can you try and see if #169 fixes your issues?

**Comment by thierry-tranchant** [comment]
This fixes it yes thanks ! But it made appear an error that was hidden by this one. `ActiveJob` cannot take a `ServiceActor::Result` as an argument to serialize because it does not handle `BasicObject` serialization. So I converted the actor result into hash to fix this and I don't have any issue now for the initial bug because I expect the job to be called with an hash and not an actor result anymore. But still I think your PR can be useful, `instance_of` is a nice to have in my opinion.
Wdyt ?

**Comment by sunny** [comment]
Yes, I think these changes still make sense, I’m merging them in `main`.

It makes sense to me to call `to_h` when passing it to ActiveJob. However, if you can think of a way to simplify this serialization somehow we could perhaps add it (does `ActiveJob` check for a specific method, for example?).

**Comment by viralpraxis** [comment]
> It makes sense to me to call to_h when passing it to ActiveJob. However, if you can think of a way to simplify this serialization somehow we could perhaps add it (does ActiveJob check for a specific method, for example?).

To integrate `ServiceActor::Result` into activejob (de)seriazliation you'd register a [custom serializer](https://github.com/rails/rails/blob/main/activejob/lib/active_job/serializers/object_serializer.rb)

But I'd say casting to a hash explicitly is better: in case of custom serializer [you'd have to take care of complex hash values by yourself](https://github.com/rails/rails/blob/main/activejob/lib/active_job/arguments.rb#L71-L108) (e.g. custom `ActiveRecord` instances to `GlobalID::Identification`)

**Comment by sunny** [comment]
Both `#hash` and `#instance_of?` added in 3.9.4 🚀
