### ISSUE TITLE
Inputs to Actor must be symbol keys.

### ISSUE THREAD

**Issue by MSILycanthropy** [sunny/actor#170]
Noticed this little oddity when bumping up to the latest version of the gem during some infra upgrades. 

Currently, the behavior is such that string keys just don't work, for example 

```ruby
class HelloWorld < Actor
  input :guy

  def call
    puts "Hello World, #{guy}"
  end
end

HelloWorld.result(guy: 'Fred')
HelloWorld.result('guy' => 'Fred')
```

The top call works, the bottom call yields `The "guy" input on "HelloWorld" is missing (ServiceActor::ArgumentError)`. 

The reason this feels weird to me is a bit rails-related. We've got a few places in our application that we take some request params and pass them into an actor, something like,

```ruby 
class GreetingsController < ApplicationController
  def create
    HelloWorld.result(**greeting_params)
  end
  
  private 
  
  def greeting_params
    params.require(:guy)
  end
```

Could very well be a change on the Ruby or Rails side that broke this. Currently reproducing this with Rails 7.2 and Ruby 3.3.4. 

Potentially introduced with the move away from OpenStruct?

**Comment by sunny** [comment]
Good call, this is since the move from OpenStruct which is more lax regarding arguments.
