### ISSUE TITLE
Proposal: allow chainable actor-like objects to be "basic"

### ISSUE THREAD

**Issue by viralpraxis** [sunny/actor#181]
Currently, we allow objects passed to play to be called as long as they respond to `call` with an arity of 1:

https://github.com/sunny/actor/blob/5071274aceceb03aabbd447b23c0b8bee2dda67b/lib/service_actor/playable.rb#L101

However, there are multiple method invocations (`is_a?`) that are not available in direct subclasses of `BasicObject`. This seems avoidable (see the attached PR). Unfortunately, using `rescue NoMethodError` feels a bit inelegant, but it appears to be the only reliable way to check if an object is 'basic' (so we should run `call` right away ) or not.

On the bright side, this patch has no measurable performance impact, as raising exceptions is not part of any hot path.

Implementation: https://github.com/sunny/actor/pull/180

**Comment by sunny** [comment]
Unfortunate that we would need to rescue here, but there’s not many ways around it I’m afraid.

I understand why it can be useful, I’d be happy to add this 👍🏻

**Comment by viralpraxis** [comment]
The [PR](https://github.com/sunny/actor/pull/180) is ready for review
