### ISSUE TITLE
En fait j'avais raison depuis le début c'est ça ?

### ISSUE THREAD

**Issue by TristeFigure** [sunny/actor#26]
Face à vos pff ?

**Comment by sunny** [comment]
Salut @TristeFigure ! De quoi parles-tu ?

**Comment by sunny** [comment]
Je ferme cette issue sur GitHub pour ne garder ici que des bugs, mais si tu as envie de discuter ou si tu as des idées pour Actor on peut en discuter sur le Slack de [ParisRB](https://rubyparis.org/).
