### ISSUE TITLE
Type example

### ISSUE THREAD

**Issue by paulomcnally** [sunny/actor#41]
Hi.

Have a question.

Where create type class?

What is the content of a type class?

**Comment by sunny** [comment]
Hi there!

When using `type:`, it ensures that the arguments you give to the actor _inherit_ from the classes that you give.

For example:

```rb
class UpdateUser < Actor
  input :user, type: "User"
  input :age, type: ["Integer", "Float"]

  # …
end

class User < ApplicationRecord
  # …
end
```

This would accept `UpdateUser.call(user: User.new, age: 12)` but raise an error when calling `UpdateUser.call(user: 1, age: "12").

**Comment by paulomcnally** [comment]
So it has to be a class that inherits from ApplicationRecord?

Doesn't work like graphql-ruby that you can create types even without inheriting from ApplicationRecord?

**Comment by sunny** [comment]
No, it can be any class, in the example I’m also using `Integer`, `Float` which don’t inherit from `ApplicationRecord`.

**Comment by paulomcnally** [comment]
How would you do a class UserNotApplicationRecord that has name string, email string, and password string?

```
...
input :user, type: 'UserNotApplicationRecord'
...
```

**Comment by sunny** [comment]
Yep, just like that 👍🏻 

Here’s a full example with a custom class:

```rb
class GreetUser < Actor
  input :user, type: "User"

  def call
    puts "Hello #{user.name}!"
  end
end

class User
  def initialize(name:, email:, password:)
    @name = name
    @email = email
    @password = password
  end

  attr_reader :name, :email, :password
end

user = User.new(name: "Kylo", email: "kylo@example.com", password: "upsilon1%25")

GreetUser.call(user: "wrong")
# => ServiceActor::ArgumentError: Input user on GreetUser must be of type User but was String

GreetUser.call(user: user)
# => Hello Kylo!
```

**Comment by paulomcnally** [comment]
Ha ok, dont it's a deep validator.

You can't tell inside User which name has a specific type or which age is of type integer.

Validation is at the highest level only.

This has resolved my doubts.

Thanks.
