### ISSUE TITLE
"default" and "in" input attributes don't behave as expected.

### ISSUE THREAD

**Issue by Buzzkill-McSquare** [sunny/actor#43]
If I have an `input` that has both the `default` and `in` attribute, and I call the actor without that input, I would expect the default to be used. Instead I get a `ServiceActor::ArgumentError` because my lack of input doesn't satisfy the `in:` property.

### Example

```ruby
class MyActor < Actor
  input :word, default: "one", in: ["one", "two", "three"]
  ...
end
```

When calling this actor like `MyActor.call`, I would expect the `word` variable to be set to `"one"`.

**Comment by sunny** [comment]
Thanks for reporting this issue! It is now fixed and released in 3.1.2 ✨
