### ISSUE TITLE
[Discuss] actor default: option not so useful for my usage.

### ISSUE THREAD

**Issue by zw963** [sunny/actor#48]
Hi, i am a user come from `interactor`, i use this gem for all my service , until, i meet a issue, i want a guarantee to ensure pass correct name input into my service, so, i switch to use service_actor, one if the reason is, this gem not use 'activesupport'.

Following is my code:

I define my service like this:

```rb
class RetrieveStocks < Actor
  input :sort_column
  input :sort_direction
  input :page, default: '1'
  input :per, default: '20'
  input :stock_name

  def call
    # ...
  end
end
```

Then, invoke my service in my roda routers, like this:

```rb
     sort_column, sort_direction, stock_name, page, per = r.params.values_at('sort_column', 'sort_direction', 'stock_name', 'page', 'per')
	 
      result = RetrieveStocks.(
        sort_column: sort_column,
        sort_direction: sort_direction,
        page: page,
        per: per,
        stock_name: stock_name,
      )
```

 Following is my issue, because above `page`, `per` is come from request params, 
so, them maybe string, or nil(when user not use paginate),  when pass both
of them into service, if request not use paginate, will pass page and per as nil.
like following:

```rb
      result = RetrieveStocks.(
        sort_column: sort_column,
        sort_direction: sort_direction,
        page: nil,
        per: nil,
      )

```

For this case, what i want is, use page/per default value, but, it not work.

AFAIK, the only solution is,  run `compact!` before passed in.

```rb
      result = RetrieveStocks.({
        sort_column: sort_column,
        sort_direction: sort_direction,
        page: nil,
        per: nil,
		}.compact!)
```

But i consider this solution is not good, so, just curious, what is the expected way to do this?

Thank you.

-------------------------
EDIT:

I workaround this issue use following code.

```rb
params = r.params.slice('sort_column', 'sort_direction', 'stock_name', 'page', 'per')

result = RetrieveStocks.(params)

```

It works anyway, though, i still curious, how to handle this case when use with actor.

**Comment by sunny** [comment]
Hi @zw963!

In Actor, the defaults are just like the default keyword values in Ruby. E.g.:

```rb
def serve_dish(name: "fries")
  puts "Enjoy your #{name.inspect}"
end

class ServeDish < Actor
  input :name, default: "fries"

  def call
    puts "Enjoy your #{name.inspect}"
  end
end

serve_dish
# => Enjoy your "fries"
ServeDish.()
# => Enjoy your "fries"

serve_dish(name: nil)
# => Enjoy your nil
ServeDish.(name: nil)
# => Enjoy your nil
```

In cases like these using `compact` or `slice` before passing `nil` argument works well, just like you did.

If you’d like to treat `nil` as being the default, you could also do this like so:

```rb
class ServeDish < Actor
  input :name, default: nil

  def call
    puts "Enjoy your #{name_or_default.inspect}"
  end

  def name_or_default
    name.nil? ? "fries" : name
  end
end

ServeDish.()
# => Enjoy your "fries"
ServeDish.(name: nil)
# => Enjoy your "fries"
```

**Comment by zw963** [comment]
Thank you for excellent explain.

But, my slice solution exists another issue.

Let's us said we have a service like this, `stock_name` is not always exists.

```rb
class RetrieveStocks < Actor
  input :sort_column, default: 'next_earnings_date'
  input :sort_direction, default: 'asc'
  input :page, default: '1'
  input :per, default: '20'
  input :stock_name

  def call
  # ...
  end
end
```

Assume invoke this service like this:

RetriveStocks.call, it will raise error because
`stock_name` no default value.

But, for my service logic, if no `stock_name` provided, it should not
search base on stock_name instead, the only solution is, give nil as default value, 

```rb
class RetrieveStocks < Actor
  input :sort_column, default: 'next_earnings_date'
  input :sort_direction, default: 'asc'
  input :page, default: '1'
  input :per, default: '20'
  input :stock_name, default: nil

  def call
  # ...
  end
end
```

But, this means, all input 'MUST' have default value, so, here is a choice dilemma ...

if pass in all, will meet passed in nil issue.
if not pass in(as use slice), have to add default: option to all input ...

**Comment by sunny** [comment]
To disallow `nil` can actually use [`allow_nil: false`](https://github.com/sunny/actor#allow-nil) or the [`type:`](https://github.com/sunny/actor#types) option.

```rb
class RetrieveStocks < Actor
  input :stock_name, default: nil, allow_nil: false
  input :sort_column, default: 'next_earnings_date', type: 'String'

  def call
    puts "Stock name: #{stock_name}, Sort: #{sort_column}"
  end
end

RetrieveStocks.call
# => ServiceActor::ArgumentError: The input "stock_name" on RetrieveStocks does not allow nil values

RetrieveStocks.call(stock_name: nil)
# => ServiceActor::ArgumentError: The input "stock_name" on RetrieveStocks does not allow nil values

RetrieveStocks.call(stock_name: "Apple", sort_column: nil)
# => ServiceActor::ArgumentError: The input "sort_column" on RetrieveStocks does not allow nil values

RetrieveStocks.call(stock_name: "Apple")
# => Stock name: Apple, Sort: next_earnings_date
```

**Comment by zw963** [comment]
Thanks a lot for explain, i will use this gem several days, and switch all my service from interactor to it.

If still have question, i will discuss here.

Thank you.

**Comment by zw963** [comment]
After switch to several of my service to actor, following is some note:

1. When i invoke service from roda router, i can use like following directly. (no need slice or compact)

```rb
result = RetrieveInsiderHistory.call(r.params)
```

because it seem like actor can assure if one arg not statement use input, it not accessable in service object.
and r.params never return return value as nil

2.  most of my input can not specify type,  because those args come from params, as following:
```rb
class RetrieveInsiderHistory < Actor
  input :days, default: '7'
  input :sort_column, default: 'date'
  input :sort_direction, default: 'desc'
  input :stock_name, default: nil
  input :stock_id, default: nil, type: Integer
  input :insider_id, default: nil, type: Integer
```

in fact, `days` should be a integer, but i have to use string instead, because, if specify type: Integer for `days`, i have to handle it
before pass to it., like this:

```rb
days = r.params['days']
if days.present?
  days = days.to_i
else
  days = 7
end

result = RetrieveInsiderHistory.call(days: days)


that not good, because i have to write dirty logic outside service object for make type: Integer can pass.
I really should write those logic in service object instead, 

e.g  if we have a handler option:

```rb
input :days, handler: ->  { if _1.present? ? _1.to_i : 7 }
```

3.  i have to specify default option for all my input, even, as following case

```rb
 input :stock_id, default: nil, type: Integer
```

I have to specify `default: nil` + `type: integer` for my logic still work.

because if for cases user not passed in :stock_id in params, i need avoid raise error, and use nil in service for determinate.

Anyway, i don't know if i misunderstood or misusage somethings, it a little strange ...

**Comment by sunny** [comment]
For #2 you could accept several types and override the handler method to transform into an integer:

```rb
class RetrieveInsiderHistory < Actor
  input :days, default: 7, type: [Integer, String]
  
  def call
    puts "#{days.inspect} days"
  end

  private

  def days
    result.days.to_i
  end
end

RetrieveInsiderHistory.call
#  => "7 days"

RetrieveInsiderHistory.call(days: 99)
RetrieveInsiderHistory.call(days: "99")
#  => "99 days"
```

For #3 it’s because when you are asking for a specific type it assumes you want this type and don’t want nils. So you could write it any of these two ways:

```rb
input :stock_id, type: Integer, default: nil
# or
input :stock_id, type: Integer, allow_nil: false
```

**Comment by zw963** [comment]
> For #2 you could accept several types and override the handler method to transform into an integer:

It works!



> ```ruby
> input :stock_id, type: Integer, allow_nil: false
> ```

This way raise error when user not pass :stock_id in.

ServiceActor::ArgumentError: Input insider_id on RetrieveInsiderHistory is missing

so, the only way is use `default: nil`, and business logic is decide use `if :stock_id` inside service object.

**Comment by zw963** [comment]
I switch all my service to use actor now.

Finally, i add all my input with `type` and `default` option,like this

```rb
class RetrieveInsiderHistory < Actor
  input :days, default: 7, type: [Integer, String]
  input :sort_column, default: 'date', type: String
  input :sort_direction, default: 'desc', type: String
  input :stock_name, default: nil, type: String
  input :stock_id, default: nil, type: Integer
  input :insider_id, default: nil, type: Integer
  # ...
end
 
```

a little tediously, but, anyway, it useful, and more clear for find out what service object accepted.

There still a issue, when i run test, get many warn message like this:

```
/home/zw963/Stocks/marketbet_crawler/app/services/retrieve_insider_history.rb:97: warning: method redefined; discarding old days
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/service_actor-3.1.2/lib/service_actor/attributable.rb:26: warning: previous definition of days was here
```

If this gem want user override exists same name method this way, it should do some hack for avoid produce those warning.
the offical recommand way for this is to add a alias. as following code, (i copy from [sequel](https://github.com/jeremyevans/sequel/blob/master/lib/sequel/extensions/blank.rb) gem).

you can check discuss here.

https://groups.google.com/g/sequel-talk/c/fwa1Pwye_CY/m/DANKiBGOBQAJ

**Comment by zw963** [comment]
Another issue, please check following example.

```rb
# i assign result.institutions = ??? in this service.
result = RetrieveInstitutions.result(params)

if result.success?
    @institutions = result.some_method # But i never defined this method in above service, but when invoke it, not raise any error, just return nil, this is not acceptable?
end
```

**Comment by sunny** [comment]
> If this gem want user override exists same name method this way, it should do some hack for avoid produce those warning.

Thank for the link, didn’t know about that hack! I’d be happy to accept a patch with a test that could remove this warning.

> But when invoke it, not raise any error, just return nil

Indeed, that is a side effect of using an OpenStruct to store the set of results. I’d be happy for a patch that would raise an error in that case.

**Comment by zw963** [comment]
let us discuss another issue in new issue.
