### ISSUE TITLE
[Discuss] Why we need the output: option as describe on README?

### ISSUE THREAD

**Issue by zw963** [sunny/actor#49]
after i read [output](https://github.com/sunny/actor#outputs) section in README, i have a question.

do we need this? i found it works as interactor, following is a example

```rb
class RetrieveStocks < Actor
  input :stock_name, default: nil

  def call
     stocks = Stock.where(:stocks[:name] => stock_name)

    if stocks.empty?
      fail!(message: "no stocks!")
    else
	  # we can assign use a setter like this, why we need output?
      result.stocks = stocks
    end
  end
end

params = r.params.slice('sort_column', 'sort_direction', 'stock_name', 'page', 'per')

result = RetrieveStocks.call(params)

if result.success?
   # get assigned value, it works
  @stocks = result.stocks
end

```

Thank you.

**Comment by sunny** [comment]
Absolutely, you can call `result.stocks =` without defining any outputs.

Using `output` is useful if you want to document what you are outputting or if you want to add some constraints to your outputs to make sure they are set correctly. Also you can use `self.` instead of `result.` which is a few characters less.

But all of that is optional.

**Comment by zw963** [comment]
> Absolutely, you can call `result.stocks =` without defining any outputs.
> 
> Using `output` is useful if you want to document what you are outputting or if you want to add some constraints to your outputs to make sure they are set correctly. Also you can use `self.` instead of `result.` which is a few characters less.
> 
> But all of that is optional.

Thank you, maybe we should mention this on document.

**Comment by zw963** [comment]
BTW:  From my point, i thought use self not so clearly than use result for this case, i always prefer to use result way.

**Comment by sunny** [comment]
Yeah, it can make things clearer sometimes to use `result`, especially when coming from Interactor :)
