### ISSUE TITLE
Invoking undefined methods on a result does not raise errors

### ISSUE THREAD

**Issue by zw963** [sunny/actor#53]
please check following example.

```rb
# i assign result.institutions = ??? in this service.
result = RetrieveInstitutions.result(params)

if result.success?
    @institutions = result.institutions1 # But i never defined this method in above service, but when invoke it, not raise any error, just return nil, this is not acceptable?
end
```

Above result.institutions1 never raise any error, just return nil, which make `result.success?` almost no any means for this case.

**Comment by zw963** [comment]
> Indeed, that is a side effect of using an OpenStruct to store the set of results. I’d be happy for a patch that would raise an error in that case.

I thought there no easy way to fix this if use OpenStruct object, becuse OS use method_missing implement this, it performance bad too, so, how to resolve this issue? defined a new method missing in Result class?

consider this is a big issue for me, so, the question is:   if we must use OpenStruct to achieve this? we set each name use input, 
use OS if a overkill decision ?

**Comment by sunny** [comment]
Perhaps to drop OpenStruct we can use either `method_missing` or define methods on the result set as it is being passed through.

**Comment by zw963** [comment]
> define methods on the result set as it is being passed through.

I thought this approach is better, anyway, i consider this is a big issue, i use service_actor instead of Interactor, 
and add input, one import purpose is avoid mistakes, but this can hidden mistakes

**Comment by sunny** [comment]
@zw963 Do you want to try and implement this?

**Comment by zw963** [comment]
Sorry, i am not using Ruby recent days, instead, i am a Crystal fans

**Comment by sunny** [comment]
No worries, enjoy Crystal! :)

**Comment by grdmnt** [comment]
@sunny Ive had this issue before when using OpenStruct with our own PORO Service class. I resolved this by running with a Struct with a field called `result` and place all output fields into that as a hash. This wouldnt be a direct solution as we dont want to remove the dynamic creation of methods as it will break existing code. 

I'm wondering if it would make sense to add a separate defined field and put all output in a hash there. This should mirror dynamically added fields. It would also help in stubbing the service results as you can do a `double_instance` that new method. 

Let me know what you think as I'm currently keen on using actor and help contribute

**Comment by sunny** [comment]
The underlying code can use a hash, but the result should continue to be able to receive methods. How are you thinking of mapping these methods to the hash?

**Comment by grdmnt** [comment]
Yep definitely, the result should continue to act as it is. Sorry got my thoughts mixed up with the other issue with the stubbed outputs, which we can solve by doing the one I mentioned above. 

Going back to the original issue for invoking undefined methods, I would use a Hash to manage all the outputs and use method_missing and work around that. 

Just a quick thought dump on this, I would imagine it looking like:

```
class Result
  attr_accessor :result_hash
  
  def method_missing
    # check if symbol is in result hash, else call super which should raise an error.
  end
end
```

I'm going to tinker around a bit if I can come up with something better.

**Comment by grdmnt** [comment]
I found something interesting, but I'm not very familiar around doing metaprogramming (I try to avoid them as much as possible). 

We can do something like this:

```
 class Result
  def add(symbol, value)
     singleton_class.class_eval { attr_accessor symbol.to_sym }
     send("#{symbol}=", value)
  end
end
```
This would result into different instances of `Result` having separate methods depending on what we add per instance of it.

**Comment by sunny** [comment]
Oh nice, that looks like a very promising way to add these methods without relying on `method_missing`, especially since we use `input` and `output` to define these methods from our result sets.

**Comment by grdmnt** [comment]
Let me know what you think, I'll give it a go when I get some free time sometime for the next 2 weeks.

**Comment by sunny** [comment]
Please have a go at it, that sounds like a good solution! 🙌🏻

**Comment by grdmnt** [comment]
Hi @sunny sorry wasn't able to work on this due to sudden work changes. Happy to help contribute to the idea, but can't code for this for the meantime.

**Comment by sunny** [comment]
No worries! You can follow notifications on #124 if you want to follow the discussion about Openstruct specifically 👍🏻
