### ISSUE TITLE
Ruby 2.3

### ISSUE THREAD

**Issue by paulomcnally** [sunny/actor#55]
Hello. Is it possible to add support for ruby 2.3?

I need to use fail_on but my project uses ruby 2.3

Uploading to ruby 2.4 is in the backlog. Apparently we will do it in a few months.

My alternative is to fork and upload a gem momentarily.

I can also fork and use github on the Gemfile but I don't like the idea.

**Comment by sunny** [comment]
Hi @paulomcnally!

I’m not exactly sure of the extent at which it is incompatible with 2.3, but I know there were issues adding 2.3 to the test matrix. If you can make a PR that supports 2.3 and adds tests for it, I’d be happy to include it but I'd rather not spend too much time for EOL Ruby versions.

**Comment by paulomcnally** [comment]
I'm going to work on what you mention and do PR.

Thank you very much!

**Comment by paulomcnally** [comment]
Definitely the ideal is to update our version of ruby.

Thank you very much for considering this option.
