### ISSUE TITLE
Evaluate conditions only once

### ISSUE THREAD

**Issue by sunny** [sunny/actor#62]
When the `if:` condition is used on `play`, the lambda is evaluated once per actor, when it should only be evaluated once before playing the whole group.

```rb
class PrintThings < Actor
  play -> _ { puts "one" },
       -> _ { puts "two" },
       -> _ { puts "three" },
       if: -> _ { puts "should be evaluated only once"; true }
end

PrintThings.call
```

Current output of calling this actor:

```
should be evaluted only once
one
should be evaluted only once
two
should be evaluted only once
three
```

Expected:

```
should be evaluted only once
one
two
three
```

**Comment by pboling** [comment]
Just a passing thought, the logic behind `memoist2` gem might be helpful here.
